<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Protobuf Include="prime.proto" GrpcServices="None" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
